### ISSUE TITLE
Getting Invalid Byte Tag in Constant Pool when loading pojomatic on Tomcat 8

### ISSUE THREAD

**Issue by nwertzberger** [irobertson/pojomatic#17]
I know that Pojomatic is supposed to support Java 1.7 and above.

The error I'm getting is this at context load time: 

    2019-04-03 14:02:27,618 [omsdp140b2-startStop-1] ERROR org.apache.catalina.startup.ContextConfig- Unable to process Jar entry [module-info.class] from Jar [file:/WEB-INF/lib/pojomatic-2.2.1.jar] for annotations
    org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
	  at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:97) ~[tomcat-coyote.jar:8.5.5]
	  at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:54) ~[tomcat-coyote.jar:8.5.5]
	  at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:174) ~[tomcat-coyote.jar:8.5.5]
    <there's more here, but it's not relevant>

Some googling leads me to this, which suggests this can happen if the underlying library was compiled using a Java 9+ compiler (I think this might even come into play if the source and target are set to 1.7, since at least the library changes stay).

https://documentation.magnolia-cms.com/display/DOCS57/_known+issue+with+tomcat+8.5x+JAVA+EE+and+BCEL

I'm working on getting the version of tomcat used upgraded, but it might be helpful to know which are compiled with java 9+.

Is version 2.2.0 compiled with a pre-9 version of java? The error seems to go away if I use that.

**Comment by irobertson** [comment]
All classes in the pojomatic jar are compiled with Java 1.7, except for module-info, which necessarily is compiled with 1.9. Normally, this means pojomatic runs just fine with 1.7. Unfortunately, in your case, tomcat is trying to parse the file, presumably so it can look for annotated servlet classes and the like.

One thing that might work is to tell tomcat to skip the pojomatic jar when doing its scanning; this is probably a good thing anyway, since it will help speed up startup (you might want to exclude more than just pojomatic). Instructions are available at https://wiki.apache.org/tomcat/HowTo/FasterStartUp#Exclude_JARs_from_scanning.

**Comment by nwertzberger** [comment]
Good idea. Thanks for the suggestions! And that makes sense that that particular class is required, and that it SHOULD be backwards compatible since everything else would just ignore it.
